name: Update gist with Toggl stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # hourly
  push:
    branches: master # on push
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn install
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TOGGL_API_TOKEN: ${{ secrets.TOGGL_API_TOKEN }}
          TOGGL_WORKSPACE_ID: ${{ secrets.TOGGL_WORKSPACE_ID }}
          #FILTER_BY_TAG: 7985682
          FILTER_BY_TAG: false
          FILTER_BY_BILLABLE: no
          FILTER_BY_USER: false
